sonarr:
  image: linuxserver/sonarr
  restart: always
  ports:
    - "8989:8989"
  volumes:
    - /dev/rtc:/dev/rtc:ro
    - /srv/sonarr/config/:/config
    - /srv/media/:/tv
    - /srv/deluge/downloads:/downloads
  environment:
    - PUID=1000
    - PGID=1000